name: chatbot_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  google_fonts: ^4.0.3
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/chatbot.png
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: assets/chatbot.png
  remove_alpha_ios: true
